version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
